Support array properties in CSVs.
RedisGraph/redisgraph-bulk-loader pull request #37
Opened 2020-10-02 19:09 UTC by jeffreylovitz

This PR adds support for loading entities with array properties.

It additionally improves the trimming of whitespace in input CSVs and raises the maximum field size of inputs.

Automation will fail until https://github.com/RedisGraph/RedisGraph/pull/1365 is merged.

2020-10-03 07:00 UTC, swilly22 requested changes

2020-10-03 07:00 UTC, swilly22 commented on test/test_bulk_loader.py
> +
What about a test which enforce schema when the data is mismatched?

2020-10-05 16:42 UTC, jeffreylovitz commented on redisgraph_bulk_loader/entity_file.py
> +    IGNORE = 9
Equivalency between the type values in RedisGraph and here is mandatory, but this isn't a breaking change - the values are purely internal, and the ones greater than `ARRAY` are Python-side-only.

2020-10-05 17:08 UTC, swilly22 approved these changes

2020-10-05 17:09 UTC, swilly22 commented
@jeffreylovitz should we release a new version?

2020-10-05 17:09 UTC, merged