Bulk update
RedisGraph/redisgraph-bulk-loader pull request #53
Opened 2021-02-16 22:17 UTC by jeffreylovitz

This PR adds a `redisgraph-bulk-loader` entrypoint and logic for batch updating existing graphs with CSV files and a Cypher query.

2021-02-18 19:12 UTC, swilly22 requested changes
Nice work! please see comments, suggestions

2021-02-18 19:12 UTC, swilly22 commented on redisgraph_bulk_loader/bulk_update.py
> +                if utf8len(rows_str) + utf8len(next_line) > self.max_token_size:
computing `utf8len(rows_str)` with each iteration is expensive, compute it by maintaining the current length and adding `utf8len(next_line)` to it

2021-02-18 19:12 UTC, swilly22 commented on redisgraph_bulk_loader/bulk_update.py
> +                rows_str += next_line
Expensive, see [here](https://medium.com/python-in-plain-english/concatenating-strings-efficiently-in-python-9bfc8e8d6f6e)

2021-02-18 19:12 UTC, swilly22 commented on redisgraph_bulk_loader/bulk_update.py
> +        self.infile.close()
Consider using `with open` to scope access to the file, you can open/close the file multiple times (whenever needed)

2021-02-18 19:12 UTC, swilly22 commented on redisgraph_bulk_loader/bulk_update.py
> +@click.option('--query', '-e', help='Query to run on server')
We can execute `GRAPH.EXPLAIN` with the specified `query` to quickly detect malformed queries

2021-02-18 21:31 UTC, jeffreylovitz commented on README.md
> +|  -e   | --query TEXT             |                   Query to run on server                   |
:+1: Good catch!

2021-02-18 21:32 UTC, jeffreylovitz commented on redisgraph_bulk_loader/bulk_update.py
> +                rows_str += next_line
Oof, good to know! Thanks!

2021-02-18 21:32 UTC, jeffreylovitz commented on redisgraph_bulk_loader/bulk_update.py
> +@click.option('--query', '-e', help='Query to run on server')
:+1: Good idea!

2021-02-18 21:33 UTC, jeffreylovitz commented on redisgraph_bulk_loader/bulk_update.py
> +    def update_statistics(self, result):
I guess that is a good idea. I had thought to avoid unnecessary overhead, but really the difference should be trivial.

2021-02-19 18:51 UTC, jeffreylovitz commented on test/test_bulk_update.py
> +        self.assertIn("Cannot merge node", str(res.exception))
Accessing an invalid row index implicitly returns a NULL value, which is the same behavior as Neo's LOAD CSV.

I think there could be some fringe use cases that rely on this, as creating or setting null values is a no-op - you could introduce attributes for only some entities by using non-rectangular CSVs.

2021-02-19 20:38 UTC, swilly22 approved these changes

2021-02-19 20:38 UTC, merged