aioredis client with buffer queue
RedisGraph/redisgraph-bulk-loader pull request #63
Opened 2021-06-13 16:43 UTC by DvirDukhan

2021-06-14 17:30 UTC, jeffreylovitz requested changes
This looks good to me, a few comments!

2021-06-14 17:30 UTC, jeffreylovitz commented on redisgraph_bulk_loader/bulk_insert.py
> +@click.option('--async-requests', '-A', default=3, help='amount of async requests to be executed in parallel' )
`number` instead of `amount`

2021-06-14 17:30 UTC, jeffreylovitz commented on requirements.txt
> +anyio
Are these actually dependencies?

2021-06-14 17:30 UTC, jeffreylovitz commented on redisgraph_bulk_loader/bulk_insert.py
> +async def bulk_insert(graph, host, port, password, user, unix_socket_path, nodes, nodes_with_label, relations, relations_with_type, separator, enforce_schema, skip_invalid_nodes, skip_invalid_edges,
If I understand correctly, this function is `async` because otherwise it cannot make `async` calls?

2021-06-15 08:02 UTC, swilly22 commented
@DvirDukhan please move `async_requests` into config.py, remove it from:
`query_buf = QueryBuffer(graph, client, config, async_requests)`

2021-06-15 10:25 UTC, DvirDukhan commented on requirements.txt
> +anyio
will be removed after rebase

2021-06-15 10:25 UTC, DvirDukhan commented on redisgraph_bulk_loader/bulk_insert.py
> +async def bulk_insert(graph, host, port, password, user, unix_socket_path, nodes, nodes_with_label, relations, relations_with_type, separator, enforce_schema, skip_invalid_nodes, skip_invalid_edges,
correct

2021-09-14 13:04 UTC, closed without merging